#!/bin/bash
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -ex

#load versions
. `dirname $0`/bigtop.bom

. /etc/os-release

export JAVA_HOME=/etc/alternatives/java_sdk_17
export JAVA_TOOL_OPTIONS="-Dfile.encoding=UTF-8"
java -version
export MAVEN_OPTS="-Xms6g -Xmx6g"
MAVEN_SETTINGS=${MAVEN_SETTINGS:-/usr/local/maven-3.9.10/conf/settings.xml}
echo "Starting to build Gravitino ${GRAVITINO_VERSION}..."
./gradlew build -PpythonVersion=3.9 -x test --gradle-user-home /root/.gradle
./gradlew compileDistribution
./gradlew assembleDistribution
export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.312.b07-2.el8_5.aarch64

rm -rf binary
mkdir binary
tar -C binary --strip-components=1 -xzf distribution/gravitino-${GRAVITINO_VERSION}-bin.tar.gz
