#!/bin/bash
#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

set -e

# 读取 BigTop 环境变量
if [ -z "${BIGTOP_HOME}" ]; then
  BIGTOP_HOME=$(cd $(dirname ${0})/../../..; pwd)
fi

. ${BIGTOP_HOME}/etc/bigtop.bom

# 配置 Kyuubi 版本和下载地址
KYUUBI_VERSION=${KYUUBI_VERSION:-1.8.1}
KYUUBI_DIST_URL=${KYUUBI_DIST_URL:-"https://dlcdn.apache.org/kyuubi/${KYUUBI_VERSION}/apache-kyuubi-${KYUUBI_VERSION}-bin.tgz"}

# 创建构建目录
BUILD_DIR=$(pwd)/build
mkdir -p ${BUILD_DIR}
cd ${BUILD_DIR}

# 下载并解压 Kyuubi
if [ ! -f "apache-kyuubi-${KYUUBI_VERSION}-bin.tgz" ]; then
  wget ${KYUUBI_DIST_URL}
fi

tar -zxf apache-kyuubi-${KYUUBI_VERSION}-bin.tgz
cd apache-kyuubi-${KYUUBI_VERSION}-bin

# 构建 Kyuubi （如果需要从源码构建）
# ./build/mvn clean package -DskipTests

# 准备打包所需文件
mkdir -p ${BUILD_DIR}/kyuubi
cp -r * ${BUILD_DIR}/kyuubi/

# 清理不必要的文件
rm -rf ${BUILD_DIR}/kyuubi/examples
rm -rf ${BUILD_DIR}/kyuubi/docs
rm -rf ${BUILD_DIR}/kyuubi/build
